[build-system]
requires = ["setuptools", "wheel", "setuptools_scm[toml]>=6.0"]

[project]
name = "test_setup_scm"
dynamic = ["version"]

[tool.setuptools_scm]
write_to = "src/test_setup_scm/_version.py"